// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: infor.proto

public final class Infor {
  private Infor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface my_messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:my_message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string startedTime = 1;</code>
     */
    java.lang.String getStartedTime();
    /**
     * <code>string startedTime = 1;</code>
     */
    com.google.protobuf.ByteString
        getStartedTimeBytes();

    /**
     * <code>string version = 2;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 2;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>double configuredCapacity = 3;</code>
     */
    double getConfiguredCapacity();

    /**
     * <code>double dfsUsed = 4;</code>
     */
    double getDfsUsed();

    /**
     * <code>int32 fileNum = 5;</code>
     */
    int getFileNum();

    /**
     * <code>int32 replicatedFilesNum = 6;</code>
     */
    int getReplicatedFilesNum();

    /**
     * <code>int32 blockNum = 7;</code>
     */
    int getBlockNum();

    /**
     * <code>int32 livedNodeNum = 8;</code>
     */
    int getLivedNodeNum();

    /**
     * <code>int32 decommissioningNodeNum = 9;</code>
     */
    int getDecommissioningNodeNum();
  }
  /**
   * Protobuf type {@code my_message}
   */
  public  static final class my_message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:my_message)
      my_messageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use my_message.newBuilder() to construct.
    private my_message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private my_message() {
      startedTime_ = "";
      version_ = "";
      configuredCapacity_ = 0D;
      dfsUsed_ = 0D;
      fileNum_ = 0;
      replicatedFilesNum_ = 0;
      blockNum_ = 0;
      livedNodeNum_ = 0;
      decommissioningNodeNum_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private my_message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              startedTime_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 25: {

              configuredCapacity_ = input.readDouble();
              break;
            }
            case 33: {

              dfsUsed_ = input.readDouble();
              break;
            }
            case 40: {

              fileNum_ = input.readInt32();
              break;
            }
            case 48: {

              replicatedFilesNum_ = input.readInt32();
              break;
            }
            case 56: {

              blockNum_ = input.readInt32();
              break;
            }
            case 64: {

              livedNodeNum_ = input.readInt32();
              break;
            }
            case 72: {

              decommissioningNodeNum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Infor.internal_static_my_message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Infor.internal_static_my_message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Infor.my_message.class, Infor.my_message.Builder.class);
    }

    public static final int STARTEDTIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object startedTime_;
    /**
     * <code>string startedTime = 1;</code>
     */
    public java.lang.String getStartedTime() {
      java.lang.Object ref = startedTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startedTime_ = s;
        return s;
      }
    }
    /**
     * <code>string startedTime = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStartedTimeBytes() {
      java.lang.Object ref = startedTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startedTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 2;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIGUREDCAPACITY_FIELD_NUMBER = 3;
    private double configuredCapacity_;
    /**
     * <code>double configuredCapacity = 3;</code>
     */
    public double getConfiguredCapacity() {
      return configuredCapacity_;
    }

    public static final int DFSUSED_FIELD_NUMBER = 4;
    private double dfsUsed_;
    /**
     * <code>double dfsUsed = 4;</code>
     */
    public double getDfsUsed() {
      return dfsUsed_;
    }

    public static final int FILENUM_FIELD_NUMBER = 5;
    private int fileNum_;
    /**
     * <code>int32 fileNum = 5;</code>
     */
    public int getFileNum() {
      return fileNum_;
    }

    public static final int REPLICATEDFILESNUM_FIELD_NUMBER = 6;
    private int replicatedFilesNum_;
    /**
     * <code>int32 replicatedFilesNum = 6;</code>
     */
    public int getReplicatedFilesNum() {
      return replicatedFilesNum_;
    }

    public static final int BLOCKNUM_FIELD_NUMBER = 7;
    private int blockNum_;
    /**
     * <code>int32 blockNum = 7;</code>
     */
    public int getBlockNum() {
      return blockNum_;
    }

    public static final int LIVEDNODENUM_FIELD_NUMBER = 8;
    private int livedNodeNum_;
    /**
     * <code>int32 livedNodeNum = 8;</code>
     */
    public int getLivedNodeNum() {
      return livedNodeNum_;
    }

    public static final int DECOMMISSIONINGNODENUM_FIELD_NUMBER = 9;
    private int decommissioningNodeNum_;
    /**
     * <code>int32 decommissioningNodeNum = 9;</code>
     */
    public int getDecommissioningNodeNum() {
      return decommissioningNodeNum_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStartedTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, startedTime_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
      }
      if (configuredCapacity_ != 0D) {
        output.writeDouble(3, configuredCapacity_);
      }
      if (dfsUsed_ != 0D) {
        output.writeDouble(4, dfsUsed_);
      }
      if (fileNum_ != 0) {
        output.writeInt32(5, fileNum_);
      }
      if (replicatedFilesNum_ != 0) {
        output.writeInt32(6, replicatedFilesNum_);
      }
      if (blockNum_ != 0) {
        output.writeInt32(7, blockNum_);
      }
      if (livedNodeNum_ != 0) {
        output.writeInt32(8, livedNodeNum_);
      }
      if (decommissioningNodeNum_ != 0) {
        output.writeInt32(9, decommissioningNodeNum_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStartedTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, startedTime_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
      }
      if (configuredCapacity_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, configuredCapacity_);
      }
      if (dfsUsed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, dfsUsed_);
      }
      if (fileNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, fileNum_);
      }
      if (replicatedFilesNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, replicatedFilesNum_);
      }
      if (blockNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, blockNum_);
      }
      if (livedNodeNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, livedNodeNum_);
      }
      if (decommissioningNodeNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, decommissioningNodeNum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Infor.my_message)) {
        return super.equals(obj);
      }
      Infor.my_message other = (Infor.my_message) obj;

      boolean result = true;
      result = result && getStartedTime()
          .equals(other.getStartedTime());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && (
          java.lang.Double.doubleToLongBits(getConfiguredCapacity())
          == java.lang.Double.doubleToLongBits(
              other.getConfiguredCapacity()));
      result = result && (
          java.lang.Double.doubleToLongBits(getDfsUsed())
          == java.lang.Double.doubleToLongBits(
              other.getDfsUsed()));
      result = result && (getFileNum()
          == other.getFileNum());
      result = result && (getReplicatedFilesNum()
          == other.getReplicatedFilesNum());
      result = result && (getBlockNum()
          == other.getBlockNum());
      result = result && (getLivedNodeNum()
          == other.getLivedNodeNum());
      result = result && (getDecommissioningNodeNum()
          == other.getDecommissioningNodeNum());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STARTEDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartedTime().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + CONFIGUREDCAPACITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getConfiguredCapacity()));
      hash = (37 * hash) + DFSUSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDfsUsed()));
      hash = (37 * hash) + FILENUM_FIELD_NUMBER;
      hash = (53 * hash) + getFileNum();
      hash = (37 * hash) + REPLICATEDFILESNUM_FIELD_NUMBER;
      hash = (53 * hash) + getReplicatedFilesNum();
      hash = (37 * hash) + BLOCKNUM_FIELD_NUMBER;
      hash = (53 * hash) + getBlockNum();
      hash = (37 * hash) + LIVEDNODENUM_FIELD_NUMBER;
      hash = (53 * hash) + getLivedNodeNum();
      hash = (37 * hash) + DECOMMISSIONINGNODENUM_FIELD_NUMBER;
      hash = (53 * hash) + getDecommissioningNodeNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Infor.my_message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Infor.my_message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Infor.my_message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Infor.my_message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Infor.my_message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Infor.my_message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Infor.my_message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Infor.my_message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Infor.my_message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Infor.my_message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Infor.my_message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Infor.my_message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Infor.my_message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code my_message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:my_message)
        Infor.my_messageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Infor.internal_static_my_message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Infor.internal_static_my_message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Infor.my_message.class, Infor.my_message.Builder.class);
      }

      // Construct using Infor.my_message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        startedTime_ = "";

        version_ = "";

        configuredCapacity_ = 0D;

        dfsUsed_ = 0D;

        fileNum_ = 0;

        replicatedFilesNum_ = 0;

        blockNum_ = 0;

        livedNodeNum_ = 0;

        decommissioningNodeNum_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Infor.internal_static_my_message_descriptor;
      }

      public Infor.my_message getDefaultInstanceForType() {
        return Infor.my_message.getDefaultInstance();
      }

      public Infor.my_message build() {
        Infor.my_message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Infor.my_message buildPartial() {
        Infor.my_message result = new Infor.my_message(this);
        result.startedTime_ = startedTime_;
        result.version_ = version_;
        result.configuredCapacity_ = configuredCapacity_;
        result.dfsUsed_ = dfsUsed_;
        result.fileNum_ = fileNum_;
        result.replicatedFilesNum_ = replicatedFilesNum_;
        result.blockNum_ = blockNum_;
        result.livedNodeNum_ = livedNodeNum_;
        result.decommissioningNodeNum_ = decommissioningNodeNum_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Infor.my_message) {
          return mergeFrom((Infor.my_message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Infor.my_message other) {
        if (other == Infor.my_message.getDefaultInstance()) return this;
        if (!other.getStartedTime().isEmpty()) {
          startedTime_ = other.startedTime_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getConfiguredCapacity() != 0D) {
          setConfiguredCapacity(other.getConfiguredCapacity());
        }
        if (other.getDfsUsed() != 0D) {
          setDfsUsed(other.getDfsUsed());
        }
        if (other.getFileNum() != 0) {
          setFileNum(other.getFileNum());
        }
        if (other.getReplicatedFilesNum() != 0) {
          setReplicatedFilesNum(other.getReplicatedFilesNum());
        }
        if (other.getBlockNum() != 0) {
          setBlockNum(other.getBlockNum());
        }
        if (other.getLivedNodeNum() != 0) {
          setLivedNodeNum(other.getLivedNodeNum());
        }
        if (other.getDecommissioningNodeNum() != 0) {
          setDecommissioningNodeNum(other.getDecommissioningNodeNum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Infor.my_message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Infor.my_message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object startedTime_ = "";
      /**
       * <code>string startedTime = 1;</code>
       */
      public java.lang.String getStartedTime() {
        java.lang.Object ref = startedTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startedTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string startedTime = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStartedTimeBytes() {
        java.lang.Object ref = startedTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startedTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string startedTime = 1;</code>
       */
      public Builder setStartedTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startedTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string startedTime = 1;</code>
       */
      public Builder clearStartedTime() {
        
        startedTime_ = getDefaultInstance().getStartedTime();
        onChanged();
        return this;
      }
      /**
       * <code>string startedTime = 1;</code>
       */
      public Builder setStartedTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        startedTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 2;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private double configuredCapacity_ ;
      /**
       * <code>double configuredCapacity = 3;</code>
       */
      public double getConfiguredCapacity() {
        return configuredCapacity_;
      }
      /**
       * <code>double configuredCapacity = 3;</code>
       */
      public Builder setConfiguredCapacity(double value) {
        
        configuredCapacity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double configuredCapacity = 3;</code>
       */
      public Builder clearConfiguredCapacity() {
        
        configuredCapacity_ = 0D;
        onChanged();
        return this;
      }

      private double dfsUsed_ ;
      /**
       * <code>double dfsUsed = 4;</code>
       */
      public double getDfsUsed() {
        return dfsUsed_;
      }
      /**
       * <code>double dfsUsed = 4;</code>
       */
      public Builder setDfsUsed(double value) {
        
        dfsUsed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double dfsUsed = 4;</code>
       */
      public Builder clearDfsUsed() {
        
        dfsUsed_ = 0D;
        onChanged();
        return this;
      }

      private int fileNum_ ;
      /**
       * <code>int32 fileNum = 5;</code>
       */
      public int getFileNum() {
        return fileNum_;
      }
      /**
       * <code>int32 fileNum = 5;</code>
       */
      public Builder setFileNum(int value) {
        
        fileNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fileNum = 5;</code>
       */
      public Builder clearFileNum() {
        
        fileNum_ = 0;
        onChanged();
        return this;
      }

      private int replicatedFilesNum_ ;
      /**
       * <code>int32 replicatedFilesNum = 6;</code>
       */
      public int getReplicatedFilesNum() {
        return replicatedFilesNum_;
      }
      /**
       * <code>int32 replicatedFilesNum = 6;</code>
       */
      public Builder setReplicatedFilesNum(int value) {
        
        replicatedFilesNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 replicatedFilesNum = 6;</code>
       */
      public Builder clearReplicatedFilesNum() {
        
        replicatedFilesNum_ = 0;
        onChanged();
        return this;
      }

      private int blockNum_ ;
      /**
       * <code>int32 blockNum = 7;</code>
       */
      public int getBlockNum() {
        return blockNum_;
      }
      /**
       * <code>int32 blockNum = 7;</code>
       */
      public Builder setBlockNum(int value) {
        
        blockNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 blockNum = 7;</code>
       */
      public Builder clearBlockNum() {
        
        blockNum_ = 0;
        onChanged();
        return this;
      }

      private int livedNodeNum_ ;
      /**
       * <code>int32 livedNodeNum = 8;</code>
       */
      public int getLivedNodeNum() {
        return livedNodeNum_;
      }
      /**
       * <code>int32 livedNodeNum = 8;</code>
       */
      public Builder setLivedNodeNum(int value) {
        
        livedNodeNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 livedNodeNum = 8;</code>
       */
      public Builder clearLivedNodeNum() {
        
        livedNodeNum_ = 0;
        onChanged();
        return this;
      }

      private int decommissioningNodeNum_ ;
      /**
       * <code>int32 decommissioningNodeNum = 9;</code>
       */
      public int getDecommissioningNodeNum() {
        return decommissioningNodeNum_;
      }
      /**
       * <code>int32 decommissioningNodeNum = 9;</code>
       */
      public Builder setDecommissioningNodeNum(int value) {
        
        decommissioningNodeNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 decommissioningNodeNum = 9;</code>
       */
      public Builder clearDecommissioningNodeNum() {
        
        decommissioningNodeNum_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:my_message)
    }

    // @@protoc_insertion_point(class_scope:my_message)
    private static final Infor.my_message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Infor.my_message();
    }

    public static Infor.my_message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<my_message>
        PARSER = new com.google.protobuf.AbstractParser<my_message>() {
      public my_message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new my_message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<my_message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<my_message> getParserForType() {
      return PARSER;
    }

    public Infor.my_message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013infor.proto\"\324\001\n\nmy_message\022\023\n\013startedT" +
      "ime\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022\032\n\022configured" +
      "Capacity\030\003 \001(\001\022\017\n\007dfsUsed\030\004 \001(\001\022\017\n\007fileN" +
      "um\030\005 \001(\005\022\032\n\022replicatedFilesNum\030\006 \001(\005\022\020\n\010" +
      "blockNum\030\007 \001(\005\022\024\n\014livedNodeNum\030\010 \001(\005\022\036\n\026" +
      "decommissioningNodeNum\030\t \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_my_message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_my_message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_message_descriptor,
        new java.lang.String[] { "StartedTime", "Version", "ConfiguredCapacity", "DfsUsed", "FileNum", "ReplicatedFilesNum", "BlockNum", "LivedNodeNum", "DecommissioningNodeNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
